version: "3"
services:
  odin:
    image: mbround18/valheim-odin:latest
    build:
      context: .
      dockerfile: ./Dockerfile.odin
    volumes:
    - odin-output:/data/odin/target/release
  valheim:
    depends_on:
      - odin
    image: mbround18/valheim:latest
    environment:
      PORT: 2456
      NAME: "theMIGHTYvalheim-01"
      PASSWORD: ""
      TZ: "Europe/Berlin"
      AUTO_UPDATE: 1
      AUTO_UPDATE_SCHEDULE: "0 3 * * *"
      AUTO_BACKUP: 1
      AUTO_BACKUP_SCHEDULE: "*/15 * * * *"
      AUTO_BACKUP_REMOVE_OLD: 1
      AUTO_BACKUP_DAYS_TO_LIVE: 2
      AUTO_BACKUP_ON_UPDATE: 1
      AUTO_BACKUP_ON_SHUTDOWN: 1
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "2456:2456/udp"
      - "2457:2457/udp"
      - "2458:2458/udp"
    volumes:
    - /opt/valheim/saves:/home/steam/.config/unity3d/IronGate/Valheim
    - /opt/valheim/server:/home/steam/valheim
    - /opt/valheim/backups:/home/steam/backups
    - odin-output:/home/steam/.odin

volumes:
  odin-output:
